config/routes.rb
TestApp::Application.routes.draw do
  get "plants2/index"
  get "plants2/:id" => 'plants2#show', as: 'plants2'

  resources :plants2, :only => [:destroy] do
    collection do
      delete 'destroy_multiple'
    end
  end

  
  resources :plants
  root :to => 'plants#index'

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessible :comment, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plants2_controller.rb
class Plants2Controller < ApplicationController
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @plants }
    end
  end

  def show

  end

  def destroy
  	binding.pry
  	@plant = Plant.find(params[:id])
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants2_index_path }
      format.json 
    end
  end

  def destroy_multiple
  	Plant.destroy(params[:plant])

  	respond_to do |format|
  		format.html { redirect_to plants2_index_path }
  		format.json { head :no_content }
  	end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @plants }
    end
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plant }
    end
  end

  # GET /plants/new
  # GET /plants/new.json
  def new
    @plant = Plant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plant }
    end
  end

  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render json: @plant, status: :created, location: @plant }
      else
        format.html { render action: "new" }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.json
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    # binding.pry
    @plant = Plant.find(params[:id])
    @plant.destroy
    @plants = Plant.all

    respond_to do |format|
      format.html { redirect_to plants_url }
      format.js 
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants2_helper.rb
module Plants2Helper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "application", "plants" %>

  <%= csrf_meta_tags %>
</head>
<script>

</script>
<body>

<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/plants/_form.html.erb
<script>
var editor = new wysihtml5.Editor("wysihtml5-textarea", { // id of textarea element
  toolbar:      "wysihtml5-toolbar", // id of toolbar element
  parserRules:  wysihtml5ParserRules // defined in parser rules set 
});
</script>

<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, class: "wysihtml5-textarea"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<% @plants.each do |plant| %>
  <tr>
    <td><%= plant.name %></td>
    <td><%= plant.comment %></td>
    <td><%= link_to 'Show', plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, confirm: 'Are you sure?', :method => :delete, :remote => true, :class => "delete_plant" %></td>
  </tr>
<% end %>

app/views/plants/destroy.js.erb
// var id = "<%= @plant %>"

$('.show').html("<%=j render 'plants/plant' %>");

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table class="show">
  <tr>
    <th>Name</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render 'plants/plant' %>

</table>

<br />

<%= link_to 'New Plant', new_plant_path %>

<!-- 
<nav>
	<ul>
		<li><a href="#">Home</a></li>
		<li><a href="#">Tutorials</a>
			<ul>
				<li><a href="#">Photoshop</a></li>
				<li><a href="#">Illustrator</a></li>
				<li><a href="#">Web Design</a></li>
			</ul>
		</li>
		<li><a href="#">Articles</a>
			<ul>
				<li><a href="#">Web Design</a></li>
				<li><a href="#">User Experience</a></li>
			</ul>
		</li>
		<li><a href="#">Inspiration</a></li>
	</ul>
</nav> -->

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plant.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @plant.comment %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/plants2/_plant.erb
<% @plants.each do |plant| %>
  <tr>
    <td><%= check_box_tag "plant[]", plant.id %></td>
    <td><%= plant.name %></td>
    <td><%= plant.comment %></td>
    <td><%= link_to 'Show', plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plants2_path(plant), confirm: 'Are you sure?', :method => :delete, :class => "delete_plant" %></td>
  </tr>

<% end %>

app/views/plants2/index.html.erb
<h1>Plants2#index</h1>

<h2>Listing plants</h2>

<table class="show">
  <tr>
  	<th></th>
    <th>Name</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= form_tag destroy_multiple_plants2_index_path, method: :delete do %>
<%#= render 'plants2/plant' %>
	<% @plants.each do |plant| %>
	  <tr>
	    <td><%= check_box_tag "plant[]", plant.id %></td>
	    <td><%= plant.name %></td>
	    <td><%= plant.comment %></td>
	    <td><%= link_to 'Show', plant %></td>
	    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
	    <td><%= link_to 'Destroy', plants2_path(plant), confirm: 'Are you sure?', :method => :delete, :class => "delete_plant" %></td>
	  </tr>

	<% end %>

</table>

<br />
<%= submit_tag "Delete" %>
<%= link_to 'New Plant', new_plant_path %>

<% end %>

<%#= button_to "Delete", {controller: :plants2, action: :destroy, id: "delete_button"}, method: :delete %>